import "server-only";
import { extractText, getDocumentProxy } from "unpdf";
import { callLLM } from "./fallover";
import {
  ResumeExtractionSchema,
  RESUME_SYSTEM_INSTRUCTION,
  buildResumePrompt,
  type ResumeExtraction,
} from "./prompts";
import {
  INTEREST_OPTIONS,
  SKILL_OPTIONS,
} from "@/lib/onboarding-options";

/**
 * Parse a resume PDF into structured skills + role buckets.
 *
 * Flow:
 *   1. Extract text from the PDF locally (no LLM call) using `unpdf` —
 *      a small, serverless-friendly wrapper around Mozilla's pdf.js.
 *   2. Send the text through callLLM(), which gives us automatic
 *      Gemini → Groq fallover on rate limits / quota errors.
 *
 * Why not Gemini multimodal directly:
 *   When Gemini's free quota is exhausted, multimodal has no fallover (Groq
 *   doesn't accept PDF input). Going via text means a quota miss on Gemini
 *   transparently routes to Groq Llama 3.1 8B and the user still gets their
 *   skills extracted.
 *
 * Trade-off:
 *   Scanned PDFs (no embedded text layer) lose OCR. Most resumes are
 *   text-PDFs generated by Word / Google Docs / Canva, so this is rare.
 *   When it does happen we surface a clear error rather than silently
 *   returning empty skills.
 */
export type ResumeExtractionResult = ResumeExtraction & { raw_text: string };

export async function parseResumePdf(
  pdfBytes: Uint8Array,
): Promise<ResumeExtractionResult> {
  const text = await extractPdfText(pdfBytes);

  if (text.trim().length < 80) {
    throw new Error(
      "This PDF has no readable text — likely a scanned resume. Try exporting from Word / Google Docs / Canva so the text layer is preserved.",
    );
  }

  const result = await callLLM({
    prompt: buildResumePrompt(text, INTEREST_OPTIONS, SKILL_OPTIONS),
    schema: ResumeExtractionSchema,
    systemInstruction: RESUME_SYSTEM_INSTRUCTION,
    maxTokens: 2500,
    groqModel: "openai/gpt-oss-120b",
    primaryProvider: "groq",
  });

  return { ...normalize(result.data), raw_text: text };
}

async function extractPdfText(bytes: Uint8Array): Promise<string> {
  const pdf = await getDocumentProxy(bytes);
  const { text } = await extractText(pdf, { mergePages: true });
  // unpdf can return string or string[] depending on mergePages; normalize.
  return Array.isArray(text) ? text.join("\n") : text;
}

/** Lowercase, dedupe, drop one-char garbage tokens. */
function normalize(input: ResumeExtraction): ResumeExtraction {
  const cleanSkills = uniq(
    input.skills
      .map((s) => s.toLowerCase().trim())
      .filter((s) => s.length >= 2 && s.length <= 40),
  ).slice(0, 40);

  const cleanRoles = uniq(
    input.roles_of_interest
      .map((s) => s.trim())
      .filter((s) => s.length >= 2 && s.length <= 60),
  ).slice(0, 10);

  return {
    skills: cleanSkills,
    roles_of_interest: cleanRoles,
    estimated_seniority: input.estimated_seniority,
    key_achievements: input.key_achievements.slice(0, 3),
  };
}

function uniq<T>(arr: T[]): T[] {
  return Array.from(new Set(arr));
}
